---
# handlers file for nftables

# (re)Start will be called at first run or when systemd units are modified
- name: Restart nftables service
  ansible.builtin.systemd:
    daemon_reload: '{{ (nftables__register_systemd_service.changed | default(False)) or
                       (nftables__register_fail2ban_service.changed | default(False)) or
                       (nftables__register_fix_systemd_target.changed | default(False)) or
                       (nftables__register_systemd_custom.changed | default(False)) }}'
    state: 'restarted'
    name: '{{ nft_service_name }}'
  async: 5
  poll: 2
  when:
    - not ansible_check_mode
    - ansible_service_mgr == 'systemd'
    - nft_service_manage

# Reload will avoid to loose Nftables rulebase if an invalid syntax is added
- name: Reload nftables service
  ansible.builtin.systemd:
    state: 'reloaded'
    name: '{{ nft_service_name }}'
  async: 5
  poll: 2
  when:
    - not ansible_check_mode
    - ansible_service_mgr == 'systemd'
    - nft_service_manage
    - not nftables__register_systemd_service.changed
