---
name: release

on:
  release:
    types:
      - published
    secrets:
      ANSIBLE_GALAXY_TOKEN:
        required: true

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v4
      - name: galaxy
        uses: averagebit/action-galaxy@1.0.0
        with:
          galaxy_token: ${{ secrets.ANSIBLE_GALAXY_TOKEN }}
